[package]
name = "k2hash_rust"
version = "1.0.2"
edition = "2021"
description = "Official k2hash Rust Driver"
build = "build.rs"
license = "MIT"

[dependencies]
libc = "0.2"

# https://doc.rust-lang.org/cargo/reference/features.html#the-features-section
[features]
default-features = []
